import Container from "./Container";
import SectionHeading from "./SectionHeading";

const steps = [
  {
    n: "01",
    title: "File your case",
    body: "Explain what happened, state your position and attach screenshots, photos or text evidence.",
  },
  {
    n: "02",
    title: "Hear both sides",
    body: "Your partner is summoned and gets their own chance to plead, respond and present evidence.",
  },
  {
    n: "03",
    title: "The AI court deliberates",
    body: "Independent AI jurors review evidence, consistency and fairness. The judge then delivers the final ruling.",
  },
  {
    n: "04",
    title: "Choose the judgement",
    body: "The winner picks one safe, case-relevant judgement generated by Plead — for example replacing a meal, planning a date or taking over a chore.",
  },
];

export default function HowItWorks() {
  return (
    <section id="how-it-works" aria-labelledby="how-title" className="py-20 sm:py-28">
      <Container>
        <div className="reveal">
          <SectionHeading
            id="how-title"
            eyebrow="How Plead works"
            title="From “you always…” to a verdict in four steps"
            intro="Either partner can file a case. Roles are per case, so whoever files is the plaintiff this time."
          />
        </div>
        <ol className="mt-12 grid gap-5 sm:grid-cols-2 lg:grid-cols-4">
          {steps.map((s, i) => (
            <li
              key={s.n}
              className="reveal relative flex flex-col rounded-[var(--radius-card)] bg-paper p-6 shadow-[var(--shadow-card)] ring-1 ring-line"
              style={{ transitionDelay: `${i * 80}ms` }}
            >
              <span
                aria-hidden="true"
                className="mb-5 inline-flex h-12 w-12 items-center justify-center rounded-2xl bg-gradient-to-b from-[#dcb277] to-gold font-serif text-lg font-bold text-wine shadow-[inset_0_-3px_0_rgb(112_71_53/0.35)] ring-1 ring-[#b8864a]"
              >
                {s.n}
              </span>
              <h3 className="text-xl font-bold text-wine">
                <span className="sr-only">Step {s.n}: </span>
                {s.title}
              </h3>
              <p className="mt-2 leading-relaxed text-cocoa">{s.body}</p>
            </li>
          ))}
        </ol>
      </Container>
    </section>
  );
}
